### PR TITLE
Updated overhang logic to keep overhang speed

### PR DESCRIPTION
**Pull request by gravity-addiction**
during that feature layer. Moved logic to addWall() exclusively. Still needs some work when coasting is active doesn't use overhang speed.

### CODE REVIEW

**Comment by gravity-addiction** [comment]
@smartavionics I'd like to start a thread about this logic someplace away from the other thread, "Cura should never start a perimeter on an overhang #3875"

What's the best way to share gcode files?

**Comment by smartavionics** [comment]
> @smartavionics I'd like to start a thread about this logic someplace away from the other thread, "Cura should never start a perimeter on an overhang #3875"

> What's the best way to share gcode files?

How about using the PR you created as a means to communicate and you can attach files to your comments there?

**Comment by gravity-addiction** [comment]
Boy, I say boy this dude is about a sharp as a bowling ball.. We're in the PR thread already.. Thanks for the suggestion to attach the files here, so 
[salley.zip](https://github.com/smartavionics/CuraEngine/files/2185850/salley.zip)
here's a zip file. It should be to note that i've never been able to get 3mf files to load back into source versions of cura. Could be that i'm on the master Ultimaker/Cura branch.

**Comment by smartavionics** [comment]
> Boy, I say boy this dude is about a sharp as a bowling ball..

Fuck you pal, I'm not listening anymore.

**Comment by gravity-addiction** [comment]
You never wanted to work with me in the first place. Comment wasn't even directed toward you, get over yourself dude.

Edit: The more I think about it, maybe the shoe fuckin fit.. So Fuck you right back at you.

**Pull request closed without merging**
